- name: dev server Apache install
  hosts: _dev_server
  become: true
  tasks:
    - name: Apache'yi yükleyin
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat" or ansible_distribution == "Amazon"

    - name: Apache'yi başlatın ve enable edin
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

      





- name: prod server Install Docker
  hosts: _prod_server
  become: true
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version

    - name: Print Docker version
      debug:
        var: docker_version.stdout




- name: staging server Django install
  hosts: _staging_server
  become: true
  tasks:
    - name: Sistem güncellemesi
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Gerekli paketlerin yüklenmesi
      ansible.builtin.yum:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Django sanal ortamının oluşturulması
      command: python3 -m venv /home/ec2-user/django_env
      args:
        creates: /home/ec2-user/django_env

    - name: Django'nun yüklenmesi
      pip:
        name: django
        virtualenv: /home/ec2-user/django_env

    - name: Django'nun yüklenip yüklenmediğinin kontrol edilmesi
      command: /home/ec2-user/django_env/bin/python -m django --version
      register: django_version

    - name: Django sürümünü yazdır
      debug:
        var: django_version.stdout




- name: test server Install Git
  hosts: _test_server
  become: true
  tasks:
    - name: Update yum packages
      yum:
        name: "*"
        state: latest

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Verify Git installation
      command: git --version
      register: git_version

    - name: Show Git version
      debug:
        var: git_version.stdout
